### ISSUE TITLE
nodeType 111? 

### ISSUE THREAD

**Issue by kfrp** [WebReflection/uwire#2]
Hi Andrea, I'm confused as to why `node.nodeType` is being compared to `111` [here](https://github.com/WebReflection/uwire/blob/b941ad674e834fc8a864c409bf79185eda5e94cc/index.js#L21) (and in µhtml)? That's not a valid nodeType value as far as I know.  

Thanks for your help.

**Comment by WebReflection** [comment]
A wire is not a valid DOM element neither, so its type is just something that doesn’t conflict with standards.
